Transform:
  - Count
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Count: 3
    Properties:
      Tags:
        - Key: "Name"
          Value: "Test Bucket %d"
        - Key: "department"
          Value: "IT"
        - Key: "owner"
          Value: "Billy Bob"
        - Key: "cost-center"
          Value: "00186"
